#! /bin/bash
# Handy launch script for a miral-shell "desktop session"
# Usage: testrun [<build dir>] [-Xmir] [<switches passed to miral-shell>]

socket=${XDG_RUNTIME_DIR}/mir_socket
builddir=$(dirname $0)/../build/
if [ $# -gt 0 -a "${1:0:1}" != "-" -a -d "$1" ]; then builddir=$1/; shift; fi
if [ $# -gt 0 -a "$1" == "-Xmir" ]; then xmir_display=:1 shift; fi

if [ -e "${socket}" ]; then echo "Error: '${socket}' already exists"; exit 1 ;fi

sudo ls >> /dev/null
sudo DISPLAY=${xmir_display} ${builddir}bin/miral-shell --vt 4 --arw-file --file ${socket} $* &

while [ ! -e "${socket}" ]; do echo "waiting for ${socket}"; sleep 1 ;done

if [ "${xmir_display}" ]; then Xmir ${xmir_display} -rootless& fi
DISPLAY=${xmir_display} ${builddir}bin/miral-run gnome-terminal&
