#! /bin/bash
# Handy launch script for a miral "desktop session"
# Usage: testrun [<build dir>] [-kiosk] [<switches passed to miral-shell>]

socket=${XDG_RUNTIME_DIR}/mir_socket
builddir=$(dirname $0)/../build/
miral_server=miral-shell

while [ $# -gt 0 ]
do
    if [ "${1:0:1}" != "-" -a -d "$1" ]; then builddir=$1/; fi
    if [ "$1" == "-kiosk" ]; then miral_server=miral-kiosk; fi
    if [ "${1:0:2}" == "--" ]; then break; fi
    shift
done

if [ -e "${socket}" ]; then echo "Error: '${socket}' already exists"; exit 1 ;fi

sudo ls >> /dev/null
sudo LD_LIBRARY_PATH=${LD_LIBRARY_PATH} ${builddir}bin/${miral_server} --vt 4 --arw-file --file ${socket} $* &

while [ ! -e "${socket}" ]; do echo "waiting for ${socket}"; sleep 1 ;done

${builddir}bin/miral-run ${session_dbus} dbus-run-session -- gnome-terminal --app-id com.canonical.miral.Terminal
