#! /bin/bash

# Usage: testrun [<build dir> [<switches passed to miral-shell>]]

socket=${XDG_RUNTIME_DIR}/mir_socket
xmir_display=:1
builddir=$(dirname $0)/../build/
if [ $# -gt 0 ]; then builddir=$1/; shift; fi

if [ -e "${socket}" ]; then echo "Error: '${socket}' already exists"; exit 1 ;fi

sudo ls >> /dev/null
sudo DISPLAY=${xmir_display} ${builddir}bin/miral-shell --vt 4 --arw-file --file ${socket} $* &
while [ ! -e "${socket}" ]; do echo "waiting for ${socket}"; sleep 1 ;done
Xmir ${xmir_display} -rootless&
DISPLAY=${xmir_display} ${builddir}bin/miral-run gnome-terminal&
